/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 785e86c18a56d40921c40551ac37f42c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "LogSession";
	}
	interface Env {
		LOADER: WorkerLoader;
		LogSession: DurableObjectNamespace<import("./src/server").LogSession>;
	}
}
interface Env extends Cloudflare.Env {}
